#66 Verificacion de datos
DAW-ESFOT/proyecto-semestre-backend-policlassroom pull request #74
Opened 2021-08-01 20:56 UTC by NathalyBermeo97

2021-08-01 21:25 UTC, AnderSon277 commented on app/Http/Controllers/OptionController.php
answer es  boolean

2021-08-01 21:26 UTC, AnderSon277 commented on app/Http/Controllers/TopicController.php
>              'pdf' => 'required| string|max:500',
pdf es un file

2021-08-01 21:31 UTC, AnderSon277 commented on app/Http/Controllers/TopicController.php
>              'pdf' => 'required| string|max:500',
quizas hay para video un tipo link, no esto seguro

2021-08-01 21:32 UTC, AnderSon277 commented on app/Http/Controllers/TeacherController.php
> -        ]);
no faltan campos aquí?

2021-08-01 21:33 UTC, AnderSon277 commented on app/Http/Controllers/StudentController.php
> -            ]
Son todos los campos que se deben verificar al momento del register

2021-08-01 21:34 UTC, AnderSon277 commented on app/Http/Controllers/StudentController.php
> -            ]
Son todos los campos que se deben verificar al momento del register

2021-08-01 21:38 UTC, AnderSon277 requested changes
Revisa los comentarios que te dejo, y también la parte de $messages, incluyen mas errores, como el de unique, los errores de tipo de dato. Ej: Si es el campo es un string y el usuario ingresa un numero le debe regresar el mensaje de error adecuado.  Y si hay mas mejor

2021-08-01 23:36 UTC, NathalyBermeo97 commented on app/Http/Controllers/OptionController.php
ya le cambio porque no hice nada en la función store porque ya estaba la validación.

2021-08-01 23:37 UTC, NathalyBermeo97 commented on app/Http/Controllers/TopicController.php
>              'pdf' => 'required| string|max:500',
ya averiguo porque no hice nada en la función store porque ya estaba la validación, pensé que estaba bien

2021-08-02 05:44 UTC, AnderSon277 approved these changes
Good

2021-08-02 06:05 UTC, merged